FIX Improve styling of sudo mode prompt in SS3
silverstripe/silverstripe-security-extensions pull request #14
Opened 2019-08-01 03:14 UTC by ScopeyNZ

Similar level of hackiness to `silverstripe/mfa`. The simplist solution is just to incude the relevant bootstrap styling into the scss for the component. I needed to add a container in order to get the style affecting children correctly.

2019-08-01 21:47 UTC, robbieaverill approved these changes

2019-08-01 21:50 UTC, robbieaverill requested changes
Validation error messages aren't being displayed, which is a regression from this PR. We may need to adjust the markup slightly, the message is in the DOM:

![image](https://user-images.githubusercontent.com/5170590/62329741-e521aa80-b50a-11e9-998a-f153f83f243c.png)

2019-08-02 00:31 UTC, ScopeyNZ commented
Hmmmn. This isn't working on 4.4 for me either. This might be related to the bootstrap upgrade though... I'll play around with 4.3 too. Can we move this to a separate issue? It'll probably end up with a PR to the `4.0` branch anyway.

2019-08-02 01:24 UTC, robbieaverill approved these changes

2019-08-02 01:24 UTC, merged